language: python

python:
- '2.7'

install:
- make install

script:
- make check

after_success:
- coveralls

deploy:
  provider: pypi
  user: karsten-d
  password:
    secure: ht+h9ANCH+CFm3cIxzcwYakDmGQCtMd4rfw40535WiIYx2TOBN4fn/3cyRDsQOB2e4AoKYWnIYHNBTj69Lm26u2GElbThBwfjUOz9x1Dq8MIcbYj1Eaupd46Vx0nwr/uTa6woPDM5dfUR5Uwuv4j5iz3gKlXWx3HtLI62Q6GMx4Y/2oYIbN0GN0XFqwpIXT6uriXkjElk+mjC1CHP+5NRlTWjhGsWjUxsvxct2KI21Vl4cezBpdYewEYsAgZvF0wKPZrJb95cJDJd8/Cp2hI/AXUwGu2gteVFrwm9xPDwZNLZY2bceSxaptlqLbGNW85EMUJEpPwv8f6PDBRv0EZeyJjPO5QX4N7UglgonwXEb2GvRfIoa9vqHbL8uQ8tDImOi0v8yKXwkAJLx0z5KJBSr5VB5OImcWnx7cqN2tcb9LJ89U6ubo7xen/oqglaTIeafQFXFS8yDWjjGRuoLtRzgJd1ii44RJAVmzukA3uwMIM8ebSSlwLrFW/LWWGfTrGF2uBz6+KwxWZC/tmbL1srvMY44Y70vLxYi6dG1hy39POdJC3Pz2Act5url+A0667pIMVzpVvqEV8tdXLLohw+4RSIBaPILY2Tf3F1ZjQuIiCnTmecvLsblLM8EilHEXbF4pwrVPYIJIbL4zWVckY3HciVfkMyTfhftvB7StDjdE=
  on:
    tags: true
    repo: karsten-d/scapely
  distributions: sdist bdist_wheel
  skip_upload_docs: true
